# Generated by Django 5.2.4 on 2025-07-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
