# Generated by Django 5.2.4 on 2025-08-17 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_coin_discount_bill_coins_redeemed_bill_subtotal_and_more'),
        ('orders', '0003_order_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='billing.bill'),
        ),
    ]
