# Generated by Django 5.2.4 on 2025-09-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pos_order',
            field=models.BooleanField(default=False, help_text='True if this order was created from the POS screen.'),
        ),
    ]
