# Generated by Django 5.2.4 on 2025-08-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_applied_discount_bill_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='coin_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='coins_redeemed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
