# Generated by Django 5.2.4 on 2025-08-18 11:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_coin_discount_bill_coins_redeemed_bill_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
