# Generated by Django 5.2.4 on 2025-07-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('table_number', models.PositiveIntegerField(blank=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
