# Generated by Django 5.2.4 on 2025-07-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='table_number',
        ),
    ]
