# Generated by Django 5.2.4 on 2025-08-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loyalty_coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
