# Generated by Django 5.2.4 on 2025-08-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('pcs', 'Pieces')], max_length=3)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
