# Generated by Django 5.2.4 on 2025-07-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='number',
            new_name='table_number',
        ),
        migrations.RemoveField(
            model_name='table',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
