# Generated by Django 5.2.4 on 2025-07-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('role', models.CharField(choices=[('kitchen', 'Kitchen'), ('waitstaff', 'Waitstaff')], max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
