# Generated by Django 5.2.4 on 2025-07-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('waitstaff', 'Waitstaff'), ('admin', 'Admin')], max_length=50),
        ),
    ]
