# Generated by Django 5.2.4 on 2025-08-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The code customers or staff will enter (e.g., STUDENT15, DIWALI20).', max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='The percentage (e.g., 15 for 15%) or the fixed amount (e.g., 50 for ₹50).', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Only active discounts can be applied.')),
                ('requires_staff_approval', models.BooleanField(default=False, help_text='If checked, this discount must be approved by a staff member.')),
            ],
        ),
    ]
