# Generated by Django 5.2.4 on 2025-09-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='If checked, this discount is hidden from everyone except admins.'),
        ),
    ]
