# Generated by Django 5.2.4 on 2025-10-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_discount_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='minimum_bill_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The minimum bill subtotal required to apply this discount. Set to 0 for no minimum.', max_digits=10),
        ),
    ]
