from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TableViewSet

# 1. Create a router instance
router = DefaultRouter()

# 2. Register the ViewSet at the root of this app's URL space
# The r'' means it won't add any extra path segment.
router.register(r'', TableViewSet, basename='table')

# 3. The urlpatterns are the URLs generated by the router
urlpatterns = [
    path('', include(router.urls)),
]
