# Generated by Django 5.2.4 on 2025-09-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_is_available_dishingredient_dish_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_point_of_sale_only',
            field=models.BooleanField(default=False, help_text="Items in this category are hidden from the main app and only appear on the staff's POS screen."),
        ),
    ]
