# Generated by Django 5.2.4 on 2025-09-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_category_is_point_of_sale_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of the category (optional).', null=True),
        ),
    ]
