# Generated by Django 5.2.4 on 2025-10-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian')], max_length=20),
        ),
    ]
